### ISSUE TITLE
Make kalite executable anywhere.

### ISSUE THREAD

**Issue by cpauya** [learningequality/installers#30]
**Branch** Develop
**Target** 0.14.x
**Expected Behavior** The `bin/kalite` script must be executable anywhere on Mac OS X after installation.

**Tasks**
- [x] Set the `KALITE_DIR` environment variable to the `ka-lite` directory of the .app.
- [x] Set the `KALITE_PYTHON` environment variable to the `PyRun` directory of the .app.
- [ ] Symlink `/usr/local/bin/kalite` to `bin/kalite`
- [ ] Check env vars in Terminal
- [ ] Check env vars in iTerm2
- [ ] Check env vars in .app
- [ ] Check env vars in .app ran with Spotlight

References:
* [Setting environment variables in OS X?](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/588442#588442)

**Comment by cpauya** [comment]
Just found an issue where the `KALITE_DIR` and `KALITE_PYTHON` environment variables are not set when the computer is restarted.  This makes the `kalite` executable failing to work on the Terminal unless the user runs the GUI and clicks the Apply button, which is pretty cumbersome.

So far, we have these options to set the environment variables after a computer restart thereby making `kalite` executable anywhere:

1. add entries to `/etc/launchd.conf`
2. create a .plist file at `/Library/LaunchDaemons/`
3. run `launchctl setenv KALITE_DIR <path-here>` every login

Have attempted item 1 before but cannot seem to do it programmatically (and some also commented it doesn't work on OS X Yosemite 10.10 already) so I'm now working to make item 2 work.  

Hope to make a PR after a lot of testing and restarts. :smile_cat: 

References:

1. [Setting environment variables in OS X?](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/588442#588442)
1. [Setting environment variables via launchd.conf no longer works in OS X Yosemite?](http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite?lq=1)

**Comment by EdDixon** [comment]
Thanks @cpauya you know I am ready to test anything here just let me know! This might explain why the machine I have here KA Lite was in a working state but now isn't. I may have had to reboot for a recent mac update.. (not 100%) sure that ot I ran another test installer after having a working one going here. Some explanations are just too long to tell here in git but in a nutshell the installer start gui failed but issuing a kalite start managed to get the server running after which I could manage it from the menubar icon. I think I posted the full trace back as an attachment in the testing room Thursday or Friday... Thanks,
